//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatabaseProcedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseProcedures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.CrossCutting.Resources.DatabaseProcedures", typeof(DatabaseProcedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVE_TEAM_LEAVES.
        /// </summary>
        public static string APPROVE_TEAM_LEAVES {
            get {
                return ResourceManager.GetString("APPROVE_TEAM_LEAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL_EMPLOYEE_LEAVE.
        /// </summary>
        public static string CANCEL_EMPLOYEE_LEAVE {
            get {
                return ResourceManager.GetString("CANCEL_EMPLOYEE_LEAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_REIMBURSEMENT.
        /// </summary>
        public static string DELETE_REIMBURSEMENT {
            get {
                return ResourceManager.GetString("DELETE_REIMBURSEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD_PAYSLIP.
        /// </summary>
        public static string DOWNLOAD_PAYSLIP {
            get {
                return ResourceManager.GetString("DOWNLOAD_PAYSLIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F_TDSCALC_PORTAL_SELECT.
        /// </summary>
        public static string F_TDSCALC_PORTAL_SELECT {
            get {
                return ResourceManager.GetString("F_TDSCALC_PORTAL_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM_16_DOWNLOAD.
        /// </summary>
        public static string FORM_16_DOWNLOAD {
            get {
                return ResourceManager.GetString("FORM_16_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_APPOINTMENT_LETTERS.
        /// </summary>
        public static string GET_APPOINTMENT_LETTERS {
            get {
                return ResourceManager.GetString("GET_APPOINTMENT_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_AUTO_APPROVALS.
        /// </summary>
        public static string GET_AUTO_APPROVALS {
            get {
                return ResourceManager.GetString("GET_AUTO_APPROVALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_BRANCH_MAPPING_DETAILS.
        /// </summary>
        public static string GET_BRANCH_MAPPING_DETAILS {
            get {
                return ResourceManager.GetString("GET_BRANCH_MAPPING_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMP_AADHAR_PATH.
        /// </summary>
        public static string GET_EMP_AADHAR_PATH {
            get {
                return ResourceManager.GetString("GET_EMP_AADHAR_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMP_APPROVAL_TRAVEL_BYID.
        /// </summary>
        public static string GET_EMP_APPROVAL_TRAVEL_BYID {
            get {
                return ResourceManager.GetString("GET_EMP_APPROVAL_TRAVEL_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMP_APPROVED_BILLS_COUNT.
        /// </summary>
        public static string GET_EMP_APPROVED_BILLS_COUNT {
            get {
                return ResourceManager.GetString("GET_EMP_APPROVED_BILLS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMP_PAYSLIPS.
        /// </summary>
        public static string GET_EMP_PAYSLIPS {
            get {
                return ResourceManager.GetString("GET_EMP_PAYSLIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMP_PENDING_BILLS_COUNT.
        /// </summary>
        public static string GET_EMP_PENDING_BILLS_COUNT {
            get {
                return ResourceManager.GetString("GET_EMP_PENDING_BILLS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMP_PROFILE_DATA.
        /// </summary>
        public static string GET_EMP_PROFILE_DATA {
            get {
                return ResourceManager.GetString("GET_EMP_PROFILE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMPLOYEE_LEVELS.
        /// </summary>
        public static string GET_EMPLOYEE_LEVELS {
            get {
                return ResourceManager.GetString("GET_EMPLOYEE_LEVELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMPLOYEE_LOCATION.
        /// </summary>
        public static string GET_EMPLOYEE_LOCATION {
            get {
                return ResourceManager.GetString("GET_EMPLOYEE_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMPLOYEE_TDS_AMOUNT.
        /// </summary>
        public static string GET_EMPLOYEE_TDS_AMOUNT {
            get {
                return ResourceManager.GetString("GET_EMPLOYEE_TDS_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_GET_EMPLOYEE_TIME_SHEET.
        /// </summary>
        public static string GET_EMPLOYEE_TIME_SHEET {
            get {
                return ResourceManager.GetString("GET_EMPLOYEE_TIME_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMPLOYEE_TRAVEL_DT_BYID.
        /// </summary>
        public static string GET_EMPLOYEE_TRAVEL_DT_BYID {
            get {
                return ResourceManager.GetString("GET_EMPLOYEE_TRAVEL_DT_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMPLOYEE_TRAVEL_MT_DETAILS.
        /// </summary>
        public static string GET_EMPLOYEE_TRAVEL_MT_DETAILS {
            get {
                return ResourceManager.GetString("GET_EMPLOYEE_TRAVEL_MT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMPLOYEE_WORKFLOW.
        /// </summary>
        public static string GET_EMPLOYEE_WORKFLOW {
            get {
                return ResourceManager.GetString("GET_EMPLOYEE_WORKFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMPLOYEES_FOR_TRAVEL.
        /// </summary>
        public static string GET_EMPLOYEES_FOR_TRAVEL {
            get {
                return ResourceManager.GetString("GET_EMPLOYEES_FOR_TRAVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_FROM_LOCATION.
        /// </summary>
        public static string GET_FROM_LOCATION {
            get {
                return ResourceManager.GetString("GET_FROM_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_IDEMPOTENCY_ID.
        /// </summary>
        public static string GET_IDEMPOTENCY_ID {
            get {
                return ResourceManager.GetString("GET_IDEMPOTENCY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_LEAVE_INFORMATION.
        /// </summary>
        public static string GET_LEAVE_INFORMATION {
            get {
                return ResourceManager.GetString("GET_LEAVE_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_LEAVE_POLICY_INFORMATION.
        /// </summary>
        public static string GET_LEAVE_POLICY_INFORMATION {
            get {
                return ResourceManager.GetString("GET_LEAVE_POLICY_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_LEAVES_ENCASHMENT_APPROVAL.
        /// </summary>
        public static string GET_LEAVES_ENCASHMENT_APPROVAL {
            get {
                return ResourceManager.GetString("GET_LEAVES_ENCASHMENT_APPROVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_LEAVES_FOR_APPROVAL.
        /// </summary>
        public static string GET_LEAVES_FOR_APPROVAL {
            get {
                return ResourceManager.GetString("GET_LEAVES_FOR_APPROVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_LEAVES_WAIT_FOR_APPROVAL.
        /// </summary>
        public static string GET_LEAVES_WAIT_FOR_APPROVAL {
            get {
                return ResourceManager.GetString("GET_LEAVES_WAIT_FOR_APPROVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_NOTIFICATIONS.
        /// </summary>
        public static string GET_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("GET_NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_REIM_BAL_PORTAL.
        /// </summary>
        public static string GET_REIM_BAL_PORTAL {
            get {
                return ResourceManager.GetString("GET_REIM_BAL_PORTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_SEND_EMAILS.
        /// </summary>
        public static string GET_SEND_EMAILS {
            get {
                return ResourceManager.GetString("GET_SEND_EMAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_SEND_EMAILS2.
        /// </summary>
        public static string GET_SEND_EMAILS2 {
            get {
                return ResourceManager.GetString("GET_SEND_EMAILS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_SITE_NOTIFICATIONS.
        /// </summary>
        public static string GET_SITE_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("GET_SITE_NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_TEAM_EMP_LEAVES.
        /// </summary>
        public static string GET_TEAM_EMP_LEAVES {
            get {
                return ResourceManager.GetString("GET_TEAM_EMP_LEAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_TEAM_LEAVES.
        /// </summary>
        public static string GET_TEAM_LEAVES {
            get {
                return ResourceManager.GetString("GET_TEAM_LEAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_TO_LOCATION.
        /// </summary>
        public static string GET_TO_LOCATION {
            get {
                return ResourceManager.GetString("GET_TO_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_TO_LOCATION_MAPPING_MT.
        /// </summary>
        public static string GET_TO_LOCATION_MAPPING_MT {
            get {
                return ResourceManager.GetString("GET_TO_LOCATION_MAPPING_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_GET1_EMP_PAYSLIP1_SELECT.
        /// </summary>
        public static string GET1_EMP_PAYSLIP1_SELECT {
            get {
                return ResourceManager.GetString("GET1_EMP_PAYSLIP1_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT_DOWNLOAD_HISTORY.
        /// </summary>
        public static string INSERT_DOWNLOAD_HISTORY {
            get {
                return ResourceManager.GetString("INSERT_DOWNLOAD_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT_EMP_EMAIL.
        /// </summary>
        public static string INSERT_EMP_EMAIL {
            get {
                return ResourceManager.GetString("INSERT_EMP_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT_EMP_EMAIL1.
        /// </summary>
        public static string INSERT_EMP_EMAIL1 {
            get {
                return ResourceManager.GetString("INSERT_EMP_EMAIL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT_EMP_FEEDBACK.
        /// </summary>
        public static string INSERT_EMP_FEEDBACK {
            get {
                return ResourceManager.GetString("INSERT_EMP_FEEDBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT_EMP_LEAVE.
        /// </summary>
        public static string INSERT_EMP_LEAVE {
            get {
                return ResourceManager.GetString("INSERT_EMP_LEAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT_EMP_LEAVE_DETAILS.
        /// </summary>
        public static string INSERT_EMP_LEAVE_DETAILS {
            get {
                return ResourceManager.GetString("INSERT_EMP_LEAVE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT_EMP_LEAVE_ENTITLEMENT.
        /// </summary>
        public static string INSERT_EMP_LEAVE_ENTITLEMENT {
            get {
                return ResourceManager.GetString("INSERT_EMP_LEAVE_ENTITLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT_LEAVE_WORKFLOW.
        /// </summary>
        public static string INSERT_LEAVE_WORKFLOW {
            get {
                return ResourceManager.GetString("INSERT_LEAVE_WORKFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT_TRAVEL_PLAN.
        /// </summary>
        public static string INSERT_TRAVEL_PLAN {
            get {
                return ResourceManager.GetString("INSERT_TRAVEL_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_DELETE_EMP_CL_MAINBILL.
        /// </summary>
        public static string P_DELETE_EMP_CL_MAINBILL {
            get {
                return ResourceManager.GetString("P_DELETE_EMP_CL_MAINBILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) AS RECORD_COUNT FROM ISSUSER.HISTORY WHERE USERID1 = {0}.
        /// </summary>
        public static string P_G_EMPLOYEE_TIME_SHEET_COUNT {
            get {
                return ResourceManager.GetString("P_G_EMPLOYEE_TIME_SHEET_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_GET_ALL_DEPARTMENTS.
        /// </summary>
        public static string P_GET_ALL_DEPARTMENTS {
            get {
                return ResourceManager.GetString("P_GET_ALL_DEPARTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_GET_EMP_CL_AGREE_SELECT.
        /// </summary>
        public static string P_GET_EMP_CL_AGREE_SELECT {
            get {
                return ResourceManager.GetString("P_GET_EMP_CL_AGREE_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_GET_EMP_CL_MAINBILL_SELECT.
        /// </summary>
        public static string P_GET_EMP_CL_MAINBILL_SELECT {
            get {
                return ResourceManager.GetString("P_GET_EMP_CL_MAINBILL_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_GET_EMP_CL_MAINTE_SELECT.
        /// </summary>
        public static string P_GET_EMP_CL_MAINTE_SELECT {
            get {
                return ResourceManager.GetString("P_GET_EMP_CL_MAINTE_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_GET_EMPLOYEE_SCREENS.
        /// </summary>
        public static string P_GET_EMPLOYEE_SCREENS {
            get {
                return ResourceManager.GetString("P_GET_EMPLOYEE_SCREENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_GET_PORTAL_HOLIDAYS.
        /// </summary>
        public static string P_GET_PORTAL_HOLIDAYS {
            get {
                return ResourceManager.GetString("P_GET_PORTAL_HOLIDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_GET_REPORTEE_TIME_SHEET.
        /// </summary>
        public static string P_GET_REPORTEE_TIME_SHEET {
            get {
                return ResourceManager.GetString("P_GET_REPORTEE_TIME_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_GETEMPDATA_FOR_API.
        /// </summary>
        public static string P_GETEMPDATA_FOR_API {
            get {
                return ResourceManager.GetString("P_GETEMPDATA_FOR_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_LEGALBRANCH_SELECT.
        /// </summary>
        public static string P_LEGALBRANCH_SELECT {
            get {
                return ResourceManager.GetString("P_LEGALBRANCH_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_SEARCH_EMPLOYEE_PORTAL.
        /// </summary>
        public static string P_SEARCH_EMPLOYEE_PORTAL {
            get {
                return ResourceManager.GetString("P_SEARCH_EMPLOYEE_PORTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_WEB_HS_BRA_BLD_SELECT.
        /// </summary>
        public static string P_WEB_HS_BRA_BLD_SELECT {
            get {
                return ResourceManager.GetString("P_WEB_HS_BRA_BLD_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_WEB_HS_USER_SELECT.
        /// </summary>
        public static string P_WEB_HS_USER_SELECT {
            get {
                return ResourceManager.GetString("P_WEB_HS_USER_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_PAYSLIPPRINTING_PORTAL.
        /// </summary>
        public static string PAYSLIP_PRINTING {
            get {
                return ResourceManager.GetString("PAYSLIP_PRINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESS_ENCASHMENT_WORKFLOW.
        /// </summary>
        public static string PROCESS_ENCASHMENT_WORKFLOW {
            get {
                return ResourceManager.GetString("PROCESS_ENCASHMENT_WORKFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESS_LEAVE_BY_HR.
        /// </summary>
        public static string PROCESS_LEAVE_BY_HR {
            get {
                return ResourceManager.GetString("PROCESS_LEAVE_BY_HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESS_LEAVE_WORKFLOW.
        /// </summary>
        public static string PROCESS_LEAVE_WORKFLOW {
            get {
                return ResourceManager.GetString("PROCESS_LEAVE_WORKFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESS_LEAVE_WORKFLOW_1.
        /// </summary>
        public static string PROCESS_LEAVE_WORKFLOW_1 {
            get {
                return ResourceManager.GetString("PROCESS_LEAVE_WORKFLOW_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REIMBURESMENT_FILE_UPLOAD.
        /// </summary>
        public static string REIMBURESMENT_FILE_UPLOAD {
            get {
                return ResourceManager.GetString("REIMBURESMENT_FILE_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE_NOTIFICATION.
        /// </summary>
        public static string SAVE_NOTIFICATION {
            get {
                return ResourceManager.GetString("SAVE_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND_OTP_EMAIL.
        /// </summary>
        public static string SEND_OTP_EMAIL {
            get {
                return ResourceManager.GetString("SEND_OTP_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_AUTO_APPROVAL_LEAVE_REPORT.
        /// </summary>
        public static string SP_AUTO_APPROVAL_LEAVE_REPORT {
            get {
                return ResourceManager.GetString("SP_AUTO_APPROVAL_LEAVE_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_CHECK_FOR_EXSISTING_LEAVES.
        /// </summary>
        public static string SP_CHECK_FOR_EXSISTING_LEAVES {
            get {
                return ResourceManager.GetString("SP_CHECK_FOR_EXSISTING_LEAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_CHECK_FOR_LEAVES_BTW_DATES.
        /// </summary>
        public static string SP_CHECK_FOR_LEAVES_BTW_DATES {
            get {
                return ResourceManager.GetString("SP_CHECK_FOR_LEAVES_BTW_DATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_CHECK_HAS_CHILDREN.
        /// </summary>
        public static string SP_CHECK_HAS_CHILDREN {
            get {
                return ResourceManager.GetString("SP_CHECK_HAS_CHILDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_CHECK_MARITAL_STATUS.
        /// </summary>
        public static string SP_CHECK_MARITAL_STATUS {
            get {
                return ResourceManager.GetString("SP_CHECK_MARITAL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_DELETE_BRANCHMAPPING.
        /// </summary>
        public static string SP_DELETE_BRANCHMAPPING {
            get {
                return ResourceManager.GetString("SP_DELETE_BRANCHMAPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_DELETE_EMPEDUCATION_DT.
        /// </summary>
        public static string SP_DELETE_EMPEDUCATION_DT {
            get {
                return ResourceManager.GetString("SP_DELETE_EMPEDUCATION_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_DELETE_EMPEXPERIENCE_DT.
        /// </summary>
        public static string SP_DELETE_EMPEXPERIENCE_DT {
            get {
                return ResourceManager.GetString("SP_DELETE_EMPEXPERIENCE_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_DELETE_EMPFAMILY_DT.
        /// </summary>
        public static string SP_DELETE_EMPFAMILY_DT {
            get {
                return ResourceManager.GetString("SP_DELETE_EMPFAMILY_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_DELETE_LEAVE_ENCASHMENT.
        /// </summary>
        public static string SP_DELETE_LEAVE_ENCASHMENT {
            get {
                return ResourceManager.GetString("SP_DELETE_LEAVE_ENCASHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_DELETE_LEAVE_ENTITLEMENT.
        /// </summary>
        public static string SP_DELETE_LEAVE_ENTITLEMENT {
            get {
                return ResourceManager.GetString("SP_DELETE_LEAVE_ENTITLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_DELETE_LEAVE_INFOMATION.
        /// </summary>
        public static string SP_DELETE_LEAVE_INFOMATION {
            get {
                return ResourceManager.GetString("SP_DELETE_LEAVE_INFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_DELETE_POLICY_INFOMATION.
        /// </summary>
        public static string SP_DELETE_POLICY_INFOMATION {
            get {
                return ResourceManager.GetString("SP_DELETE_POLICY_INFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_DELETE_VISITDETAILS.
        /// </summary>
        public static string SP_DELETE_VISITDETAILS {
            get {
                return ResourceManager.GetString("SP_DELETE_VISITDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EDUCATION_COURCE_MT.
        /// </summary>
        public static string SP_EDUCATION_COURCE_MT {
            get {
                return ResourceManager.GetString("SP_EDUCATION_COURCE_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_BLOOD_GROUP_MT.
        /// </summary>
        public static string SP_EMP_BLOOD_GROUP_MT {
            get {
                return ResourceManager.GetString("SP_EMP_BLOOD_GROUP_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_CL_AGRE_BILLS_UPLOAD.
        /// </summary>
        public static string SP_EMP_CL_AGRE_BILLS_UPLOAD {
            get {
                return ResourceManager.GetString("SP_EMP_CL_AGRE_BILLS_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_ITR_REPORT.
        /// </summary>
        public static string SP_EMP_ITR_REPORT {
            get {
                return ResourceManager.GetString("SP_EMP_ITR_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_LEAVE_FILEUPLOAD.
        /// </summary>
        public static string SP_EMP_LEAVE_FILEUPLOAD {
            get {
                return ResourceManager.GetString("SP_EMP_LEAVE_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_PAN_REPORT.
        /// </summary>
        public static string SP_EMP_PAN_REPORT {
            get {
                return ResourceManager.GetString("SP_EMP_PAN_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_UPDATE_CONSUMED_LEAVES.
        /// </summary>
        public static string SP_EMP_UPDATE_CONSUMED_LEAVES {
            get {
                return ResourceManager.GetString("SP_EMP_UPDATE_CONSUMED_LEAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_UPLD_CAR_LEASE.
        /// </summary>
        public static string SP_EMP_UPLD_CAR_LEASE {
            get {
                return ResourceManager.GetString("SP_EMP_UPLD_CAR_LEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_UPLD_CAR_LEASE_DDT.
        /// </summary>
        public static string SP_EMP_UPLD_CAR_LEASE_DDT {
            get {
                return ResourceManager.GetString("SP_EMP_UPLD_CAR_LEASE_DDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_VERIFICATION_REPORT.
        /// </summary>
        public static string SP_EMP_VERIFICATION_REPORT {
            get {
                return ResourceManager.GetString("SP_EMP_VERIFICATION_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMPLOYEE_BRANCH_MAPPING.
        /// </summary>
        public static string SP_EMPLOYEE_BRANCH_MAPPING {
            get {
                return ResourceManager.GetString("SP_EMPLOYEE_BRANCH_MAPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMPLOYEE_LEAVE_BALANCE.
        /// </summary>
        public static string SP_EMPLOYEE_LEAVE_BALANCE {
            get {
                return ResourceManager.GetString("SP_EMPLOYEE_LEAVE_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMPLOYEE_LEAVE_ENTITLEMENTS.
        /// </summary>
        public static string SP_EMPLOYEE_LEAVE_ENTITLEMENTS {
            get {
                return ResourceManager.GetString("SP_EMPLOYEE_LEAVE_ENTITLEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMPLOYEE_LEAVE_REPORT.
        /// </summary>
        public static string SP_EMPLOYEE_LEAVE_REPORT {
            get {
                return ResourceManager.GetString("SP_EMPLOYEE_LEAVE_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMPLOYEE_REORTING_STRUCTURE.
        /// </summary>
        public static string SP_EMPLOYEE_REORTING_STRUCTURE {
            get {
                return ResourceManager.GetString("SP_EMPLOYEE_REORTING_STRUCTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_FILTEREDUCOURSE_MT.
        /// </summary>
        public static string SP_FILTEREDUCOURSE_MT {
            get {
                return ResourceManager.GetString("SP_FILTEREDUCOURSE_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ACTIVE_SCREENS.
        /// </summary>
        public static string SP_GET_ACTIVE_SCREENS {
            get {
                return ResourceManager.GetString("SP_GET_ACTIVE_SCREENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ADDQUALIFICATION_MT.
        /// </summary>
        public static string SP_GET_ADDQUALIFICATION_MT {
            get {
                return ResourceManager.GetString("SP_GET_ADDQUALIFICATION_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ALL_ACTIVE_BRANCHES.
        /// </summary>
        public static string SP_GET_ALL_ACTIVE_BRANCHES {
            get {
                return ResourceManager.GetString("SP_GET_ALL_ACTIVE_BRANCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ALL_DEPARTMENTS_PMS.
        /// </summary>
        public static string SP_GET_ALL_DEPARTMENTS_PMS {
            get {
                return ResourceManager.GetString("SP_GET_ALL_DEPARTMENTS_PMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ALL_FROM_LOCATIONS.
        /// </summary>
        public static string SP_GET_ALL_FROM_LOCATIONS {
            get {
                return ResourceManager.GetString("SP_GET_ALL_FROM_LOCATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ALL_LEAVE_REPORT.
        /// </summary>
        public static string SP_GET_ALL_LEAVE_REPORT {
            get {
                return ResourceManager.GetString("SP_GET_ALL_LEAVE_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ALL_LOCATION_MAPPINGS.
        /// </summary>
        public static string SP_GET_ALL_LOCATION_MAPPINGS {
            get {
                return ResourceManager.GetString("SP_GET_ALL_LOCATION_MAPPINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_BRANCHES_BY_OFFICE_TYPE.
        /// </summary>
        public static string SP_GET_BRANCHES_BY_OFFICE_TYPE {
            get {
                return ResourceManager.GetString("SP_GET_BRANCHES_BY_OFFICE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMAILOTP_VERIFICATION.
        /// </summary>
        public static string SP_GET_EMAILOTP_VERIFICATION {
            get {
                return ResourceManager.GetString("SP_GET_EMAILOTP_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMP_LEAVE_DETAILS.
        /// </summary>
        public static string SP_GET_EMP_LEAVE_DETAILS {
            get {
                return ResourceManager.GetString("SP_GET_EMP_LEAVE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMP_LEAVE_FILE_DETAILS.
        /// </summary>
        public static string SP_GET_EMP_LEAVE_FILE_DETAILS {
            get {
                return ResourceManager.GetString("SP_GET_EMP_LEAVE_FILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMP_LEAVES_AF_TODATE.
        /// </summary>
        public static string SP_GET_EMP_LEAVES_AF_TODATE {
            get {
                return ResourceManager.GetString("SP_GET_EMP_LEAVES_AF_TODATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMP_LEAVES_BALANCE.
        /// </summary>
        public static string SP_GET_EMP_LEAVES_BALANCE {
            get {
                return ResourceManager.GetString("SP_GET_EMP_LEAVES_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMP_LEAVES_BF_STDATE.
        /// </summary>
        public static string SP_GET_EMP_LEAVES_BF_STDATE {
            get {
                return ResourceManager.GetString("SP_GET_EMP_LEAVES_BF_STDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMP_LEAVES_BY_TYPE.
        /// </summary>
        public static string SP_GET_EMP_LEAVES_BY_TYPE {
            get {
                return ResourceManager.GetString("SP_GET_EMP_LEAVES_BY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMP_PROJECT_DETAILS.
        /// </summary>
        public static string SP_GET_EMP_PROJECT_DETAILS {
            get {
                return ResourceManager.GetString("SP_GET_EMP_PROJECT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMP_REPORTING_MANAGERS.
        /// </summary>
        public static string SP_GET_EMP_REPORTING_MANAGERS {
            get {
                return ResourceManager.GetString("SP_GET_EMP_REPORTING_MANAGERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMPLOYEE_BY_DESIGNATION.
        /// </summary>
        public static string SP_GET_EMPLOYEE_BY_DESIGNATION {
            get {
                return ResourceManager.GetString("SP_GET_EMPLOYEE_BY_DESIGNATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMPLOYEE_HR_DETAILS.
        /// </summary>
        public static string SP_GET_EMPLOYEE_HR_DETAILS {
            get {
                return ResourceManager.GetString("SP_GET_EMPLOYEE_HR_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMPLOYEE_KRA_INFO.
        /// </summary>
        public static string SP_GET_EMPLOYEE_KRA_INFO {
            get {
                return ResourceManager.GetString("SP_GET_EMPLOYEE_KRA_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMPLOYEE_LEAVE_TYPES.
        /// </summary>
        public static string SP_GET_EMPLOYEE_LEAVE_TYPES {
            get {
                return ResourceManager.GetString("SP_GET_EMPLOYEE_LEAVE_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMPLOYEE_LEAVES.
        /// </summary>
        public static string SP_GET_EMPLOYEE_LEAVES {
            get {
                return ResourceManager.GetString("SP_GET_EMPLOYEE_LEAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMPLOYEE_PROFILE.
        /// </summary>
        public static string SP_GET_EMPLOYEE_PROFILE {
            get {
                return ResourceManager.GetString("SP_GET_EMPLOYEE_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_FREQUENCIES.
        /// </summary>
        public static string SP_GET_FREQUENCIES {
            get {
                return ResourceManager.GetString("SP_GET_FREQUENCIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_FROM_LOCATIONS.
        /// </summary>
        public static string SP_GET_FROM_LOCATIONS {
            get {
                return ResourceManager.GetString("SP_GET_FROM_LOCATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_HELP_DOCUMENTS.
        /// </summary>
        public static string SP_GET_HELP_DOCUMENTS {
            get {
                return ResourceManager.GetString("SP_GET_HELP_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_HR_BRANCHES.
        /// </summary>
        public static string SP_GET_HR_BRANCHES {
            get {
                return ResourceManager.GetString("SP_GET_HR_BRANCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_HRR_BRANCHES_RMS.
        /// </summary>
        public static string SP_GET_HRR_BRANCHES_RMS {
            get {
                return ResourceManager.GetString("SP_GET_HRR_BRANCHES_RMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ITR_UPLOADS.
        /// </summary>
        public static string SP_GET_ITR_UPLOADS {
            get {
                return ResourceManager.GetString("SP_GET_ITR_UPLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_LEAVE_ENCASHMENT.
        /// </summary>
        public static string SP_GET_LEAVE_ENCASHMENT {
            get {
                return ResourceManager.GetString("SP_GET_LEAVE_ENCASHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_LEAVE_ENTITLEMENT.
        /// </summary>
        public static string SP_GET_LEAVE_ENTITLEMENT {
            get {
                return ResourceManager.GetString("SP_GET_LEAVE_ENTITLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_LEAVE_REASONS.
        /// </summary>
        public static string SP_GET_LEAVE_REASONS {
            get {
                return ResourceManager.GetString("SP_GET_LEAVE_REASONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_LEAVE_TRANSACTIONS.
        /// </summary>
        public static string SP_GET_LEAVE_TRANSACTIONS {
            get {
                return ResourceManager.GetString("SP_GET_LEAVE_TRANSACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_LEAVE_TYPES_BY_OFC.
        /// </summary>
        public static string SP_GET_LEAVE_TYPES_BY_OFC {
            get {
                return ResourceManager.GetString("SP_GET_LEAVE_TYPES_BY_OFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_MAPPED_LOCATIONS.
        /// </summary>
        public static string SP_GET_MAPPED_LOCATIONS {
            get {
                return ResourceManager.GetString("SP_GET_MAPPED_LOCATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_MNGR_APRVL_LEAVE_RECENT.
        /// </summary>
        public static string SP_GET_MNGR_APRVL_LEAVE_RECENT {
            get {
                return ResourceManager.GetString("SP_GET_MNGR_APRVL_LEAVE_RECENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_NSL_EMPLOYEE_PROFILE.
        /// </summary>
        public static string SP_GET_NSL_EMPLOYEE_PROFILE {
            get {
                return ResourceManager.GetString("SP_GET_NSL_EMPLOYEE_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_NSL_EMPLOYEE_PROFILES.
        /// </summary>
        public static string SP_GET_NSL_EMPLOYEE_PROFILES {
            get {
                return ResourceManager.GetString("SP_GET_NSL_EMPLOYEE_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_OFFICE_TYPE.
        /// </summary>
        public static string SP_GET_OFFICE_TYPE {
            get {
                return ResourceManager.GetString("SP_GET_OFFICE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_PAYROLL_PERIOD.
        /// </summary>
        public static string SP_GET_PAYROLL_PERIOD {
            get {
                return ResourceManager.GetString("SP_GET_PAYROLL_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_PENDING_REVIEW_INFO.
        /// </summary>
        public static string SP_GET_PENDING_REVIEW_INFO {
            get {
                return ResourceManager.GetString("SP_GET_PENDING_REVIEW_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_RESIGNED_EMPLOYEES.
        /// </summary>
        public static string SP_GET_RESIGNED_EMPLOYEES {
            get {
                return ResourceManager.GetString("SP_GET_RESIGNED_EMPLOYEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_REVIEWER_PENDING_REVIEW_INFO.
        /// </summary>
        public static string SP_GET_REVIEWER_PENDING_REVIEW_INFO {
            get {
                return ResourceManager.GetString("SP_GET_REVIEWER_PENDING_REVIEW_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ROLE_SCREENS.
        /// </summary>
        public static string SP_GET_ROLE_SCREENS {
            get {
                return ResourceManager.GetString("SP_GET_ROLE_SCREENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_TEAM_MEMBERS.
        /// </summary>
        public static string SP_GET_TEAM_MEMBERS {
            get {
                return ResourceManager.GetString("SP_GET_TEAM_MEMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_TOLOCATION_MAPPING_MT.
        /// </summary>
        public static string SP_GET_TOLOCATION_MAPPING_MT {
            get {
                return ResourceManager.GetString("SP_GET_TOLOCATION_MAPPING_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_UTILIZED_ONDUTIES.
        /// </summary>
        public static string SP_GET_UTILIZED_ONDUTIES {
            get {
                return ResourceManager.GetString("SP_GET_UTILIZED_ONDUTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_INS_UPD_KPI_KRA_MAPPING.
        /// </summary>
        public static string SP_INS_UPD_KPI_KRA_MAPPING {
            get {
                return ResourceManager.GetString("SP_INS_UPD_KPI_KRA_MAPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_INSERT_LEAVE_ENCASHMENT.
        /// </summary>
        public static string SP_INSERT_LEAVE_ENCASHMENT {
            get {
                return ResourceManager.GetString("SP_INSERT_LEAVE_ENCASHMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_INSERT_LEAVE_INFOMATION.
        /// </summary>
        public static string SP_INSERT_LEAVE_INFOMATION {
            get {
                return ResourceManager.GetString("SP_INSERT_LEAVE_INFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_INSERT_LOGIN_TRIES.
        /// </summary>
        public static string SP_INSERT_LOGIN_TRIES {
            get {
                return ResourceManager.GetString("SP_INSERT_LOGIN_TRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_INSERT_POLICY_INFOMATION.
        /// </summary>
        public static string SP_INSERT_POLICY_INFOMATION {
            get {
                return ResourceManager.GetString("SP_INSERT_POLICY_INFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_ITR_EMP_FILEUPLOAD.
        /// </summary>
        public static string SP_ITR_EMP_FILEUPLOAD {
            get {
                return ResourceManager.GetString("SP_ITR_EMP_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KRA_INSERT_UPDATE.
        /// </summary>
        public static string SP_KRA_INSERT_UPDATE {
            get {
                return ResourceManager.GetString("SP_KRA_INSERT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_LEAVE_DETAILS_BYID.
        /// </summary>
        public static string SP_LEAVE_DETAILS_BYID {
            get {
                return ResourceManager.GetString("SP_LEAVE_DETAILS_BYID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_LEAVE_REPORT.
        /// </summary>
        public static string SP_LEAVE_REPORT {
            get {
                return ResourceManager.GetString("SP_LEAVE_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_M_BLOODRELATION_MT.
        /// </summary>
        public static string SP_M_BLOODRELATION_MT {
            get {
                return ResourceManager.GetString("SP_M_BLOODRELATION_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_M_EDUCATION_MT.
        /// </summary>
        public static string SP_M_EDUCATION_MT {
            get {
                return ResourceManager.GetString("SP_M_EDUCATION_MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_PAN_EMP_FILEUPLOAD.
        /// </summary>
        public static string SP_PAN_EMP_FILEUPLOAD {
            get {
                return ResourceManager.GetString("SP_PAN_EMP_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_POR_UPDATE_EMAIL.
        /// </summary>
        public static string SP_POR_UPDATE_EMAIL {
            get {
                return ResourceManager.GetString("SP_POR_UPDATE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE_STAGE.SP_SAVE_EMP_DRIVING_LICENSE.
        /// </summary>
        public static string SP_SAVE_EMP_DRIVING_LICENSE {
            get {
                return ResourceManager.GetString("SP_SAVE_EMP_DRIVING_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE_STAGE.SP_SAVE_EMP_VERIFICATION.
        /// </summary>
        public static string SP_SAVE_EMP_VERIFICATION {
            get {
                return ResourceManager.GetString("SP_SAVE_EMP_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE_STAGE.SP_SAVE_EMPLOYEE_AADHAAR.
        /// </summary>
        public static string SP_SAVE_EMPLOYEE_AADHAAR {
            get {
                return ResourceManager.GetString("SP_SAVE_EMPLOYEE_AADHAAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE_STAGE.SP_SAVE_EMPLOYEE_BANK_ACCOUNT.
        /// </summary>
        public static string SP_SAVE_EMPLOYEE_BANK_ACCOUNT {
            get {
                return ResourceManager.GetString("SP_SAVE_EMPLOYEE_BANK_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_EMPLOYEE_BRANCH.
        /// </summary>
        public static string SP_SAVE_EMPLOYEE_BRANCH {
            get {
                return ResourceManager.GetString("SP_SAVE_EMPLOYEE_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE_STAGE.SP_SAVE_EMPLOYEE_PAN.
        /// </summary>
        public static string SP_SAVE_EMPLOYEE_PAN {
            get {
                return ResourceManager.GetString("SP_SAVE_EMPLOYEE_PAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_FROM_LOCATION.
        /// </summary>
        public static string SP_SAVE_FROM_LOCATION {
            get {
                return ResourceManager.GetString("SP_SAVE_FROM_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_KEY_RESULT_AREA.
        /// </summary>
        public static string SP_SAVE_KEY_RESULT_AREA {
            get {
                return ResourceManager.GetString("SP_SAVE_KEY_RESULT_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_LEAVE_ENTITLEMENT.
        /// </summary>
        public static string SP_SAVE_LEAVE_ENTITLEMENT {
            get {
                return ResourceManager.GetString("SP_SAVE_LEAVE_ENTITLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_LOCATION_MAPPINGS.
        /// </summary>
        public static string SP_SAVE_LOCATION_MAPPINGS {
            get {
                return ResourceManager.GetString("SP_SAVE_LOCATION_MAPPINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_PERMISSIONS.
        /// </summary>
        public static string SP_SAVE_PERMISSIONS {
            get {
                return ResourceManager.GetString("SP_SAVE_PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_USER_ROLES.
        /// </summary>
        public static string SP_SAVE_USER_ROLES {
            get {
                return ResourceManager.GetString("SP_SAVE_USER_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SENT_EMAILOTP_VERIFICATION.
        /// </summary>
        public static string SP_SENT_EMAILOTP_VERIFICATION {
            get {
                return ResourceManager.GetString("SP_SENT_EMAILOTP_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_EMP_80G_FILEUPLOAD.
        /// </summary>
        public static string SP_TDS_EMP_80G_FILEUPLOAD {
            get {
                return ResourceManager.GetString("SP_TDS_EMP_80G_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_EMP_CHAPTER6_FILEUPLOAD.
        /// </summary>
        public static string SP_TDS_EMP_CHAPTER6_FILEUPLOAD {
            get {
                return ResourceManager.GetString("SP_TDS_EMP_CHAPTER6_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_EMP_DELETE_CHAPTER6FILE.
        /// </summary>
        public static string SP_TDS_EMP_DELETE_CHAPTER6FILE {
            get {
                return ResourceManager.GetString("SP_TDS_EMP_DELETE_CHAPTER6FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_EMP_DELETE_HINCOMEFILE.
        /// </summary>
        public static string SP_TDS_EMP_DELETE_HINCOMEFILE {
            get {
                return ResourceManager.GetString("SP_TDS_EMP_DELETE_HINCOMEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_EMP_DELETE_HRAFILE.
        /// </summary>
        public static string SP_TDS_EMP_DELETE_HRAFILE {
            get {
                return ResourceManager.GetString("SP_TDS_EMP_DELETE_HRAFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_EMP_DELETE_OINCOMEFILE.
        /// </summary>
        public static string SP_TDS_EMP_DELETE_OINCOMEFILE {
            get {
                return ResourceManager.GetString("SP_TDS_EMP_DELETE_OINCOMEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_EMP_HINCOME_FILEUPLOAD.
        /// </summary>
        public static string SP_TDS_EMP_HINCOME_FILEUPLOAD {
            get {
                return ResourceManager.GetString("SP_TDS_EMP_HINCOME_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_EMP_HRAFILEUPLOAD.
        /// </summary>
        public static string SP_TDS_EMP_HRAFILEUPLOAD {
            get {
                return ResourceManager.GetString("SP_TDS_EMP_HRAFILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_EMP_OINCOME_FILEUPLOAD.
        /// </summary>
        public static string SP_TDS_EMP_OINCOME_FILEUPLOAD {
            get {
                return ResourceManager.GetString("SP_TDS_EMP_OINCOME_FILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_EDUCATIONDETAILS.
        /// </summary>
        public static string SP_UPDATE_EDUCATIONDETAILS {
            get {
                return ResourceManager.GetString("SP_UPDATE_EDUCATIONDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_EMP_HR_VERIFY_STATUS.
        /// </summary>
        public static string SP_UPDATE_EMP_HR_VERIFY_STATUS {
            get {
                return ResourceManager.GetString("SP_UPDATE_EMP_HR_VERIFY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_EMP_ITR_STATUS.
        /// </summary>
        public static string SP_UPDATE_EMP_ITR_STATUS {
            get {
                return ResourceManager.GetString("SP_UPDATE_EMP_ITR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_EMP_PAN_STATUS.
        /// </summary>
        public static string SP_UPDATE_EMP_PAN_STATUS {
            get {
                return ResourceManager.GetString("SP_UPDATE_EMP_PAN_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_EMP_VERIFY_STATUS.
        /// </summary>
        public static string SP_UPDATE_EMP_VERIFY_STATUS {
            get {
                return ResourceManager.GetString("SP_UPDATE_EMP_VERIFY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_EXPERIENCEDETAILS.
        /// </summary>
        public static string SP_UPDATE_EXPERIENCEDETAILS {
            get {
                return ResourceManager.GetString("SP_UPDATE_EXPERIENCEDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_FAMILYDETAILS.
        /// </summary>
        public static string SP_UPDATE_FAMILYDETAILS {
            get {
                return ResourceManager.GetString("SP_UPDATE_FAMILYDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_LEAVE_ENTITLEMENT.
        /// </summary>
        public static string SP_UPDATE_LEAVE_ENTITLEMENT {
            get {
                return ResourceManager.GetString("SP_UPDATE_LEAVE_ENTITLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_LEAVE_INFOMATION.
        /// </summary>
        public static string SP_UPDATE_LEAVE_INFOMATION {
            get {
                return ResourceManager.GetString("SP_UPDATE_LEAVE_INFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_MAIL_SENT.
        /// </summary>
        public static string SP_UPDATE_MAIL_SENT {
            get {
                return ResourceManager.GetString("SP_UPDATE_MAIL_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_OTP_MAIL_SENT.
        /// </summary>
        public static string SP_UPDATE_OTP_MAIL_SENT {
            get {
                return ResourceManager.GetString("SP_UPDATE_OTP_MAIL_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_POLICY_INFOMATION.
        /// </summary>
        public static string SP_UPDATE_POLICY_INFOMATION {
            get {
                return ResourceManager.GetString("SP_UPDATE_POLICY_INFOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_SENT_MAIL_STATUS.
        /// </summary>
        public static string SP_UPDATE_SENT_MAIL_STATUS {
            get {
                return ResourceManager.GetString("SP_UPDATE_SENT_MAIL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_UPDATE_VISIT_APPROVEDETAILS.
        /// </summary>
        public static string SP_UPDATE_VISIT_APPROVEDETAILS {
            get {
                return ResourceManager.GetString("SP_UPDATE_VISIT_APPROVEDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_APPT_LETTER_STATUS.
        /// </summary>
        public static string UPDATE_APPT_LETTER_STATUS {
            get {
                return ResourceManager.GetString("UPDATE_APPT_LETTER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALIDATE_USER.
        /// </summary>
        public static string VALIDATE_USER {
            get {
                return ResourceManager.GetString("VALIDATE_USER", resourceCulture);
            }
        }
    }
}
