//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Investment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Investment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.CrossCutting.Resources.Investment", typeof(Investment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_ASSESSEETYPE_DETAILS.
        /// </summary>
        public static string ASSESSEE_TYPE_DETAILS {
            get {
                return ResourceManager.GetString("ASSESSEE_TYPE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_DISTRICT_DETAILS.
        /// </summary>
        public static string DISTRICT_DETAILS {
            get {
                return ResourceManager.GetString("DISTRICT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_EMP_HOUSEINCOME_DETAILS.
        /// </summary>
        public static string EMP_HOUSE_INCOME_DETAILS {
            get {
                return ResourceManager.GetString("EMP_HOUSE_INCOME_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_EMP_OTHERINCOME_DETAILS.
        /// </summary>
        public static string EMP_OTHER_INCOME_DETAILS {
            get {
                return ResourceManager.GetString("EMP_OTHER_INCOME_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_EMP_TDS_SUBHEAD_DETAILS.
        /// </summary>
        public static string EMP_TDS_SUBHEAD_DETAILS {
            get {
                return ResourceManager.GetString("EMP_TDS_SUBHEAD_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_HOUSEINCOME_DETAILS.
        /// </summary>
        public static string HOUSE_INCOME_DETAILS {
            get {
                return ResourceManager.GetString("HOUSE_INCOME_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_HRALOCATION_DETAILS.
        /// </summary>
        public static string HRA_LOCATION_DETAILS {
            get {
                return ResourceManager.GetString("HRA_LOCATION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_MANDAL_DETAILS.
        /// </summary>
        public static string MANDAL_DETAILS {
            get {
                return ResourceManager.GetString("MANDAL_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_OTHERINCOME_DETAILS.
        /// </summary>
        public static string OTHER_INCOME_DETAILS {
            get {
                return ResourceManager.GetString("OTHER_INCOME_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_EMP_HOUSEINCOME_FILE_DETAILS.
        /// </summary>
        public static string P_EMP_HOUSEINCOME_FILE_DETAILS {
            get {
                return ResourceManager.GetString("P_EMP_HOUSEINCOME_FILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_EMP_OTHERINCOME_FILE_DETAILS.
        /// </summary>
        public static string P_EMP_OTHERINCOME_FILE_DETAILS {
            get {
                return ResourceManager.GetString("P_EMP_OTHERINCOME_FILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_EMP_SECTION80G_FILE_DETAILS.
        /// </summary>
        public static string P_EMP_SECTION80G_FILE_DETAILS {
            get {
                return ResourceManager.GetString("P_EMP_SECTION80G_FILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_EMP_TDS_SUBHEAD_FILE_DETAILS.
        /// </summary>
        public static string P_EMP_TDS_SUBHEAD_FILE_DETAILS {
            get {
                return ResourceManager.GetString("P_EMP_TDS_SUBHEAD_FILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_TDS_EMP_HRA_FILE_DETAILS.
        /// </summary>
        public static string P_TDS_EMP_HRA_FILE_DETAILS {
            get {
                return ResourceManager.GetString("P_TDS_EMP_HRA_FILE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_TDS_UPDATE_80G_DETAILS.
        /// </summary>
        public static string SP_EMP_TDS_UPDATE_80G_DETAILS {
            get {
                return ResourceManager.GetString("SP_EMP_TDS_UPDATE_80G_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_TDS_UPDATEEMPDETAILS.
        /// </summary>
        public static string SP_EMP_TDS_UPDATEEMPDETAILS {
            get {
                return ResourceManager.GetString("SP_EMP_TDS_UPDATEEMPDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_TDS_UPDATEHRADETAILS.
        /// </summary>
        public static string SP_EMP_TDS_UPDATEHRADETAILS {
            get {
                return ResourceManager.GetString("SP_EMP_TDS_UPDATEHRADETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_TDS_UPDATEOTHERINCOME.
        /// </summary>
        public static string SP_EMP_TDS_UPDATEOTHERINCOME {
            get {
                return ResourceManager.GetString("SP_EMP_TDS_UPDATEOTHERINCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_TDS_UPDATESECSUBHEADS.
        /// </summary>
        public static string SP_EMP_TDS_UPDATESECSUBHEADS {
            get {
                return ResourceManager.GetString("SP_EMP_TDS_UPDATESECSUBHEADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_TDS_VERIFY_80G_DETAILS.
        /// </summary>
        public static string SP_EMP_TDS_VERIFY_80G_DETAILS {
            get {
                return ResourceManager.GetString("SP_EMP_TDS_VERIFY_80G_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_EMP_TDS_VERIFY_HRA_AMOUNT.
        /// </summary>
        public static string SP_EMP_TDS_VERIFY_HRA_AMOUNT {
            get {
                return ResourceManager.GetString("SP_EMP_TDS_VERIFY_HRA_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SECTION_80G_UPDATE.
        /// </summary>
        public static string SP_SECTION_80G_UPDATE {
            get {
                return ResourceManager.GetString("SP_SECTION_80G_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_VERIFY_HOUSE_INCOME.
        /// </summary>
        public static string SP_TDS_VERIFY_HOUSE_INCOME {
            get {
                return ResourceManager.GetString("SP_TDS_VERIFY_HOUSE_INCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_VERIFY_OTHER_INCOME.
        /// </summary>
        public static string SP_TDS_VERIFY_OTHER_INCOME {
            get {
                return ResourceManager.GetString("SP_TDS_VERIFY_OTHER_INCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_TDS_VERIFY_SUBHEAD_AMOUNT.
        /// </summary>
        public static string SP_TDS_VERIFY_SUBHEAD_AMOUNT {
            get {
                return ResourceManager.GetString("SP_TDS_VERIFY_SUBHEAD_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_STATE_DETAILS.
        /// </summary>
        public static string STATE_DETAILS {
            get {
                return ResourceManager.GetString("STATE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_EMP_80G_DETAILS.
        /// </summary>
        public static string TDS_EMP_80G_DETAILS {
            get {
                return ResourceManager.GetString("TDS_EMP_80G_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_TDS_EMP_DETAILS.
        /// </summary>
        public static string TDS_EMP_DETAILS {
            get {
                return ResourceManager.GetString("TDS_EMP_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_TDS_EMP_HRA_DETAILS.
        /// </summary>
        public static string TDS_EMP_HRA_DETAILS {
            get {
                return ResourceManager.GetString("TDS_EMP_HRA_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_TDS_SECTION_DETAILS.
        /// </summary>
        public static string TDS_SECTION_DETAILS {
            get {
                return ResourceManager.GetString("TDS_SECTION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYROLLNEW.PK_PORTAL_INVESTMENTPROOFS.P_TDS_SUBHEAD_DETAILS.
        /// </summary>
        public static string TDS_SUBHEAD_DETAILS {
            get {
                return ResourceManager.GetString("TDS_SUBHEAD_DETAILS", resourceCulture);
            }
        }
    }
}
