//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PerformanceManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PerformanceManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.CrossCutting.Resources.PerformanceManagement", typeof(PerformanceManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_ASSIGN_EMP_KRA_KPI_INFO.
        /// </summary>
        public static string SP_ASSIGN_EMP_KRA_KPI_INFO {
            get {
                return ResourceManager.GetString("SP_ASSIGN_EMP_KRA_KPI_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_ASSIGN_KRA_INFORMATION.
        /// </summary>
        public static string SP_ASSIGN_KRA_INFORMATION {
            get {
                return ResourceManager.GetString("SP_ASSIGN_KRA_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_ASSIGN_KRA_KPI_INFORMATION.
        /// </summary>
        public static string SP_ASSIGN_KRA_KPI_INFORMATION {
            get {
                return ResourceManager.GetString("SP_ASSIGN_KRA_KPI_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_CHECK_FOR_DUPLICATE_KPI.
        /// </summary>
        public static string SP_CHECK_FOR_DUPLICATE_KPI {
            get {
                return ResourceManager.GetString("SP_CHECK_FOR_DUPLICATE_KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_CHECK_FOR_DUPLICATE_KRA.
        /// </summary>
        public static string SP_CHECK_FOR_DUPLICATE_KRA {
            get {
                return ResourceManager.GetString("SP_CHECK_FOR_DUPLICATE_KRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_DELETE_KPI_INFORMATION.
        /// </summary>
        public static string SP_DELETE_KPI_INFORMATION {
            get {
                return ResourceManager.GetString("SP_DELETE_KPI_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ALL_DEPARTMENTS.
        /// </summary>
        public static string SP_GET_ALL_DEPARTMENTS {
            get {
                return ResourceManager.GetString("SP_GET_ALL_DEPARTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ALL_EMPLOYEES.
        /// </summary>
        public static string SP_GET_ALL_EMPLOYEES {
            get {
                return ResourceManager.GetString("SP_GET_ALL_EMPLOYEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ALL_KPI_INFORMATIONS.
        /// </summary>
        public static string SP_GET_ALL_KPI_INFORMATIONS {
            get {
                return ResourceManager.GetString("SP_GET_ALL_KPI_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ALL_KRA_INFORMATIONS.
        /// </summary>
        public static string SP_GET_ALL_KRA_INFORMATIONS {
            get {
                return ResourceManager.GetString("SP_GET_ALL_KRA_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ALL_KRA_KPI_MAPPINGS.
        /// </summary>
        public static string SP_GET_ALL_KRA_KPI_MAPPINGS {
            get {
                return ResourceManager.GetString("SP_GET_ALL_KRA_KPI_MAPPINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_ASSIGNED_KRA_INFO.
        /// </summary>
        public static string SP_GET_ASSIGNED_KRA_INFO {
            get {
                return ResourceManager.GetString("SP_GET_ASSIGNED_KRA_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMPLOYEE_FINAL_REVIEWS.
        /// </summary>
        public static string SP_GET_EMPLOYEE_FINAL_REVIEWS {
            get {
                return ResourceManager.GetString("SP_GET_EMPLOYEE_FINAL_REVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMPLOYEE_KRA_INFO.
        /// </summary>
        public static string SP_GET_EMPLOYEE_KRA_INFO {
            get {
                return ResourceManager.GetString("SP_GET_EMPLOYEE_KRA_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_EMPLOYEE_REVIEWS.
        /// </summary>
        public static string SP_GET_EMPLOYEE_REVIEWS {
            get {
                return ResourceManager.GetString("SP_GET_EMPLOYEE_REVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_FINAL_INIT_REVIEWS.
        /// </summary>
        public static string SP_GET_FINAL_INIT_REVIEWS {
            get {
                return ResourceManager.GetString("SP_GET_FINAL_INIT_REVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_KRA_FOR_DESIGNATION.
        /// </summary>
        public static string SP_GET_KRA_FOR_DESIGNATION {
            get {
                return ResourceManager.GetString("SP_GET_KRA_FOR_DESIGNATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_KRA_FOR_EMPLOYEE.
        /// </summary>
        public static string SP_GET_KRA_FOR_EMPLOYEE {
            get {
                return ResourceManager.GetString("SP_GET_KRA_FOR_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_MY_ASSIGNED_DEPARTMENTS.
        /// </summary>
        public static string SP_GET_MY_ASSIGNED_DEPARTMENTS {
            get {
                return ResourceManager.GetString("SP_GET_MY_ASSIGNED_DEPARTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_NON_SUBMITTED_REVIEW.
        /// </summary>
        public static string SP_GET_NON_SUBMITTED_REVIEW {
            get {
                return ResourceManager.GetString("SP_GET_NON_SUBMITTED_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_PENDING_INIT_REVIEWS.
        /// </summary>
        public static string SP_GET_PENDING_INIT_REVIEWS {
            get {
                return ResourceManager.GetString("SP_GET_PENDING_INIT_REVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_PENDING_REVIEW_INFO.
        /// </summary>
        public static string SP_GET_PENDING_REVIEW_INFO {
            get {
                return ResourceManager.GetString("SP_GET_PENDING_REVIEW_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_GET_TEAM_MEMBER_KRA.
        /// </summary>
        public static string SP_GET_TEAM_MEMBER_KRA {
            get {
                return ResourceManager.GetString("SP_GET_TEAM_MEMBER_KRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_KRA_DELETE.
        /// </summary>
        public static string SP_KRA_DELETE {
            get {
                return ResourceManager.GetString("SP_KRA_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_EMP_KRA_KPI_MAPPING.
        /// </summary>
        public static string SP_SAVE_EMP_KRA_KPI_MAPPING {
            get {
                return ResourceManager.GetString("SP_SAVE_EMP_KRA_KPI_MAPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_EMP_PERFORMANCE_REVIEW.
        /// </summary>
        public static string SP_SAVE_EMP_PERFORMANCE_REVIEW {
            get {
                return ResourceManager.GetString("SP_SAVE_EMP_PERFORMANCE_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_KPI_INFORMATION.
        /// </summary>
        public static string SP_SAVE_KPI_INFORMATION {
            get {
                return ResourceManager.GetString("SP_SAVE_KPI_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP_SAVE_KRA_INFORMATION.
        /// </summary>
        public static string SP_SAVE_KRA_INFORMATION {
            get {
                return ResourceManager.GetString("SP_SAVE_KRA_INFORMATION", resourceCulture);
            }
        }
    }
}
