import { BioMetric } from "../attendance/bio-metric.model";
import { AddressDetail } from "./address-detail.model";
import { AssetDetail } from "./asset-detail.model";
import { EducationDetail } from "./education-detail.model";
import { ExperienceDetail } from "./experience-detail.model";
import { FamilyDetail } from "./FamilyDetail";

export interface EmployeeInformation {
    Slno: number;
    EmployeeId: string;
    BioMatricRegNo: number;
    EmployeeSlno: number;
    EmpSLNo?:number;
    EmployeeName: string;
    FatherName: string;
    Dob: string;
    Doj: string;
    Category: string;
    SubCategory: string;
    Department: string;
    Designation: string;
    BranchName: string;
    Bank: string;
    Mobile: number;
    PersonalEmail: string;
    WorkEmail: string;
    AadharNo: number;
    PFUANNo: number;
    ESINo: number;
    PANNo: string;
    AccountNo: string;
    AccBranch: string;
    IFSC: string;
    BankInfoPath: string;
    PhotoPath: string;
    AadharPath: string;
    GrossSalary: number;
    EmployeeEducationDetails: EducationDetail[];
    EmployeeFamilyDetails: FamilyDetail[];
    EmployeeExperienceDetails: ExperienceDetail[];
    EmployeeAddressDetails: AddressDetail[];
    EmployeeAssetDetails: AssetDetail[];
    EmployeePhoto: string;
    EmployeeAttendance: BioMetric[];
    BIO_MATRIC_REG_NO: string;
    FinSLNo:number;
    EmpNo:string;
    UniqueNo:number;
    PBranchSLNo:number;
    UserSLNo:number;
    HeadSLNo:number;
    ReporteeCount:number;
}